services:
  minio:
    image: minio/minio:latest
    restart: always
    privileged: true
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - privnet
    volumes:
      - "/Users/action/minio:/data"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=privchat
 
networks:
  privnet:
    driver: bridge
 
